[package]
name = "grannus-platform"
description = "Platform interfaces and fake backends for Grannus"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
grannus-core = { path = "../grannus-core" }
v4l = "0.14.0"

[lints]
workspace = true
